spring.application.name=IQ-Report-Manager


# Default connection settings for elastic
spring.elasticsearch.uris=http://localhost:9200
# If security is enabled (default in recent ES versions)
spring.elasticsearch.username=elastic
spring.elasticsearch.password=S=hleH3GYlPP0YfXU8Gb
spring.elasticsearch.ssl.verification-mode=none

# for MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/report_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# for mongo
spring.data.mongodb.uri=mongodb://localhost:27017/iq_report_manager
spring.data.mongodb.database=iq_report_manager

#config db
config.db.type=MONGO

# for email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahulkarn77777@gmail.com
spring.mail.password=ucxs dpuo rndb jjsj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
