package IQ_Report_Manager.ai.planner;
//Determines which tools to call and in what order.

import IQ_Report_Manager.ai.llm.LlmService;
import IQ_Report_Manager.ai.prompt.PromptTemplate;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
     * Uses the LLM to transform natural language into an execution plan.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AgentPlanner {

    private final LlmService llmService;

    /**
     * Returns a textual plan generated by the LLM.
     * This is later parsed into structured plan objects.
     *
     * @param userMessage natural language request
     * @return textual execution plan
     */
    public String createPlan(String userMessage) {
        log.info("Creating execution plan for message: {}", userMessage);

        String prompt = PromptTemplate.PLANNER_PROMPT + "\n\nUser Request:\n" + userMessage;

        String plan = llmService.generate(PromptTemplate.SYSTEM_PROMPT, prompt);

        log.debug("Generated execution plan: {}", plan);

        return plan;
    }
}

