package IQ_Report_Manager.ai.dto;

//Structured response returned to clients.
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Final response returned by the AI agent.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentResponse {

    /**
     * SUCCESS / FAILED / NEEDS_CLARIFICATION
     */
    private String status;

    /**
     * Natural language response.
     */
    private String message;

    /**
     * Execution plan generated by AI.
     */
    private String executionPlan;

    /**
     * Tool execution results.
     */
    private List<ToolCallResult> toolResults;

    /**
     * Timestamp.
     */
    private LocalDateTime timestamp;
}
